# Generated by Django 4.2.6 on 2023-10-31 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_restaurant_loc_id_location_restaurant_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='owner',
            new_name='user',
        ),
    ]
