# Generated by Django 4.2.6 on 2023-11-07 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_restaurant_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='restaurant_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location', to='orders.restaurant'),
        ),
    ]
